### ISSUE TITLE
Error with Werkzeug v1.0.0

### ISSUE THREAD

**Issue by trombonehero** [mgood/flask-fanstatic#5]
When using Fanstatic with Werkzeug v1.0.0, I see the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/jon/Dev/yente/yente/__init__.py", line 8, in <module>
    from flask_fanstatic import Fanstatic
  File "/usr/local/lib/python3.7/site-packages/flask_fanstatic.py", line 4, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
```

It looks like `cached_property` might now be located in `werkzeug.utils`?

**Comment by neilkatin** [comment]
I added a pull request (#6) with a fix for this issue.
